### PR TITLE
openwrt: convert to procd

### PR DESCRIPTION
**Pull request by xabolcs**
procd is the new process management daemon and supports a [new style init script](https://openwrt.org/docs/guide-developer/procd-init-scripts).

### CODE REVIEW

**Comment by xabolcs** [comment]
I tested only the `snapclient.init` part.

**Comment by xabolcs** [comment]
After commit badaix/snapcast@a2311dfbfd1c06451ece242b7ff65a09f660f9e8 I'm wondering how to take the logging defaults into account from `/etc/default/snap{client,server}` in the init files.

procd have to run the programs in foreground. Therefore I have to set the logging sink to `system` (and also wipe out all `-d` and `--daemon` argument from `SNAPSERVER_OPTS`).

Should I override it like the `--daemon`? Should I create a `patches` directory and patch `debian/snap{client,server}.default` to add the log sink param to `SNAPSERVER_OPTS`?

**Comment by xabolcs** [comment]
> ... I'm wondering how to take the logging defaults into account ...

I decided to override them with `--logging.sink system` and `--logsink system`. Filtering out `-d` and `--daemon` is still TODO.

**Comment by badaix** [comment]
Is it recommended by OpenWRT to migrate to `procd`?
And yes: using `system` as log sink is the proper way, what about `-d`? Is it set somewhere?

**Comment by xabolcs** [comment]
As this is the new init format, I think it's recommended. Just see the [related commits in openwrt/packages](https://github.com/openwrt/packages/search?q=procd&type=Commits) repository!
I have to mention that I was unable to find an explicit recommendation on OpenWrt Wiki or in [`CONTRIBUTING.md`](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md).


I want the `-d` filter stuff because the old behavior automatically adds it to the options:
```
SNAPCLIENT_OPTS="-d $SNAPCLIENT_OPTS"
```
In turn, it forces to daemonize the process. 

That's why I want to force running the process in the foreground ...

**Comment by xabolcs** [comment]
With the upcoming v0.21 version is it feasible to refresh this PR and upstream Snapcast to OpenWrt Packages?

**Comment by db4rne** [comment]
Hi, the fork of 21.0x already happened, maybe we can still upstream this into OpenWRT packages? is there any argument against it? I'd love to help.

**Comment by db4rne** [comment]
I have started to include this into openwrt, if any of you would like to test and/or change something please contact me. you can find my branch for the snapcast package here: https://github.com/db4rne/packages/tree/snapcast

it's just the makefile from this repo (changed for version 0.24), and the procd-scripts from this PR.

**Comment by xabolcs** [comment]
@db4rne , it would be nice to include it in [OpenWrt Packages](https://github.com/openwrt/packages) repo.

I think, this PR is ready to use.

**Comment by xabolcs** [comment]
master updated to **v0.27.0**, but **develop** was left behind. Should I re-target the PR?

**Comment by xabolcs** [comment]
Retargeted the PR to `master`.

**Comment by davidandreoletti** [comment]
@xabolcs With https://github.com/badaix/snapos/pull/29, snap cast can be build for OpenWRT  23.05+.

1. Would you mind rebasing this PR ?
2. Have you tried this PR with OpenWRT 23.05 yet ?

I am keen to help test this PR on OpenWRT snapshot.

**Comment by davidandreoletti** [comment]
>  Is it recommended by OpenWRT to migrate to procd?

@badaix Yes, `procd` is [THE startup/process management facility for OpenWRT.](https://openwrt.org/docs/techref/procd)

**Comment by xabolcs** [comment]
> Have you tried this PR with OpenWRT 23.05 yet ?

I tried this PR long time ago, because of the debian files.
But I use the init files directly with OpenWrt SNAPSHOT and 23.05.

**Comment by davidandreoletti** [comment]
> But I use the init files 

@xabolcs  Do you mean the init files using procd (from this PR) were copied to your OpenWRT 23.05/snapshot device and are working as intended ?

**Comment by xabolcs** [comment]
Yup!

Just save those init files as `/etc/init.d/snap{client,server}` and they will be ready to use.

**Comment by davidandreoletti** [comment]
@xabolcs Thanks!

@badaix: @xabolcs confirmed the procd enabled init files in this PR are working on the latest OpenWRT stable and snapshot release.

Would you mind merging this PR please ?

**Comment by davidandreoletti** [comment]
@badaix This PR will take 4 min of your time max to [review its usefullness](https://github.com/badaix/snapos/pull/7#issuecomment-2028101105)/merge.

**Pull request merged**
