### PR TITLE
Fix avahi-client dependency

### PR DESCRIPTION
**Pull request by joerg-krause**
libavahi-client is automically build when avahi-daemon and dbus are
selected. Therefore, drop the avahi-client package. Additionally, add
missing dependencies for building avahi.

### CODE REVIEW

**Comment by badaix** [comment]
danke, makes sense :)

**Comment by badaix** [comment]
avahi is a beast...

**Comment by joerg-krause** [comment]
Thanks! There are some other dependency issues, yet. I will look at this further in the next days, so we can get this finally into Buildroot :smile:

**Comment by badaix** [comment]
I will update the "json for modern c++", to get rid of the "this will change with gcc7" warnings, and merge everything back into master, so that I can finally to another tagged release the next days.
I'm not quite sure how to handle the json lib anyways: 
I had to apply some patches because of incompatibility to the Android NDK toolchain (and also OpenWRT if I remember correctly). Because of this and the fact that the buildroot package is ~100MB (in the end it's just a header file), I tend to use it not as an external.

**Pull request merged**
